### ISSUE TITLE
Functions that represent matlab methods (meeg) do not work 

### ISSUE THREAD

**Issue by Y-Bezs** [spm/spm-python#17]
example 
D.fsample()
>Data type is missing or incorrect, assigning default.
>0.01

The same happens with all the methods

**Comment by vlitvak** [comment]
Probably the . overloading doesn't work in python. You could try fsample(D) instead.

**Comment by johmedr** [comment]
I think some methods still work (e.g., D.fullfile()), however they return the default value for an empty meeg. This means that for some reason, casting the Python representation of the object as an MEEG is failing... Going to look into this.

Note, `fsample(D)` would not work because methods are bound to the object and not global functions. You can use `Runtime.call('fsample', D)` if you want to force the forward call but it does not make a difference (that's what is called by `D.fsample()` anyway)

**Comment by Y-Bezs** [comment]
this one also gives the default rather than actual location
>>> D.fullfile()
Data type is missing or incorrect, assigning default.
'C:\\Users\\ybezsudnova\\spm_meeg.mat'
>>>

**Comment by johmedr** [comment]
> this one also gives the default rather than the actual location
> 
> > > > D.fullfile()
> > > > Data type is missing or incorrect, assigning default.
> > > > 'C:\Users\ybezsudnova\spm_meeg.mat'
> 
> The actual location is 'D:\opm-tutorial\tutorial\OPM_meg_001.mat'

Yes it returns the default value for an empty meeg object.

**Comment by johmedr** [comment]
The error was due to the data of the StructArray class being a list of list instead of a flat list, resulting in a cell of cell instead of a cell array, failing the construction of a non-scalar structure array. Reshaping the array to a flat array using Fortran-indexing (column major) solves the issue, and is now tested for in unit tests.
